# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emailBang.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_emailBangPlay(object):
    def setupUi(self, emailBangPlay):
        emailBangPlay.setObjectName("emailBangPlay")
        emailBangPlay.resize(557, 297)
        self.layoutWidget = QtWidgets.QWidget(emailBangPlay)
        self.layoutWidget.setGeometry(QtCore.QRect(72, 112, 363, 103))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.beginBang = QtWidgets.QPushButton(self.layoutWidget)
        self.beginBang.setObjectName("beginBang")
        self.verticalLayout.addWidget(self.beginBang)
        self.stopBang = QtWidgets.QPushButton(self.layoutWidget)
        self.stopBang.setObjectName("stopBang")
        self.verticalLayout.addWidget(self.stopBang)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setStyleSheet("QProgressBar { border: 2px solid grey; border-radius: 5px; background-color: #FFFFFF; text-align: center;}QProgressBar::chunk {background:QLinearGradient(x1:0,y1:0,x2:2,y2:0,stop:0 #666699,stop:1  #DB7093); }")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)

        self.retranslateUi(emailBangPlay)
        QtCore.QMetaObject.connectSlotsByName(emailBangPlay)

    def retranslateUi(self, emailBangPlay):
        _translate = QtCore.QCoreApplication.translate
        emailBangPlay.setWindowTitle(_translate("emailBangPlay", "短信轰炸鸡"))
        self.label.setText(_translate("emailBangPlay", "电话号码："))
        self.label_2.setText(_translate("emailBangPlay", "轰炸时间："))
        self.beginBang.setText(_translate("emailBangPlay", "开始轰炸"))
        self.stopBang.setText(_translate("emailBangPlay", "停止轰炸"))
        self.progressBar.setFormat(_translate("emailBangPlay", "Loaded  %p%"))
