# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lotteryTicket.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_twoColorPlay(object):
    def setupUi(self, twoColorPlay):
        twoColorPlay.setObjectName("twoColorPlay")
        twoColorPlay.resize(959, 779)
        self.layoutWidget = QtWidgets.QWidget(twoColorPlay)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 170, 651, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(twoColorPlay)
        QtCore.QMetaObject.connectSlotsByName(twoColorPlay)

    def retranslateUi(self, twoColorPlay):
        _translate = QtCore.QCoreApplication.translate
        twoColorPlay.setWindowTitle(_translate("twoColorPlay", "彩票统计中心"))
        self.pushButton.setText(_translate("twoColorPlay", "获取当前双色球号码"))
        self.pushButton_2.setText(_translate("twoColorPlay", "PushButton"))
        self.pushButton_3.setText(_translate("twoColorPlay", "PushButton"))
        self.pushButton_4.setText(_translate("twoColorPlay", "PushButton"))
        self.pushButton_5.setText(_translate("twoColorPlay", "PushButton"))
