# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectTools.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selectTools(object):
    def setupUi(self, selectTools):
        selectTools.setObjectName("selectTools")
        selectTools.resize(588, 364)
        self.widget = QtWidgets.QWidget(selectTools)
        self.widget.setGeometry(QtCore.QRect(160, 120, 195, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textMessage = QtWidgets.QPushButton(self.widget)
        self.textMessage.setObjectName("textMessage")
        self.horizontalLayout.addWidget(self.textMessage)
        self.twoColorBall = QtWidgets.QPushButton(self.widget)
        self.twoColorBall.setObjectName("twoColorBall")
        self.horizontalLayout.addWidget(self.twoColorBall)

        self.retranslateUi(selectTools)
        QtCore.QMetaObject.connectSlotsByName(selectTools)

    def retranslateUi(self, selectTools):
        _translate = QtCore.QCoreApplication.translate
        selectTools.setWindowTitle(_translate("selectTools", "工具选择"))
        self.textMessage.setText(_translate("selectTools", "短信轰炸机"))
        self.twoColorBall.setText(_translate("selectTools", "双色球"))
